name: publish

on:
  push:
    branches-ignore: [ main ]
    paths:
      - '.github/workflows/publish.yml'
  release:
    types: [ published ]
    
permissions:
  contents: write
  pull-requests: write

env:
  SDL_VERSION: 2.30.0 # This needs to be updated to match the SDL2 version being compiled.
  
jobs:
  prepare:
    runs-on: windows-latest

    outputs:
      version_number: ${{ steps.set_version_number.outputs.version_number }}
      version_suffix: ${{ steps.set_version_suffix.outputs.version_suffix }}
      full_version: ${{ steps.set_version_number.outputs.version_number }}${{ steps.set_version_suffix.outputs.version_suffix != '' && '-' || '' }}${{ steps.set_version_suffix.outputs.version_suffix }}

    steps:
      - name: Set version number
        id: set_version_number
        shell: bash
        run: echo "version_number=${{ env.SDL_VERSION }}" >> $GITHUB_OUTPUT

      - name: Set version suffix
        if: github.event.action != 'published'
        id: set_version_suffix
        shell: bash
        run: echo "version_suffix=preview.${{ github.run_number }}" >> $GITHUB_OUTPUT

  build-native:
    name: build (${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.os }}
    needs: prepare

    strategy:
      matrix:
        platform:
          - { name: win-x64,     os: ubuntu-latest }
          - { name: linux-x64,   os: ubuntu-latest }
      fail-fast: false
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: libsdl-org/SDL
          ref: release-${{ env.SDL_VERSION }}
        
      - name: Install dependencies (Linux)
        if: matrix.platform.name == 'linux-x64'
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev \
            libxi-dev libgl1-mesa-dev libasound2-dev libpulse-dev \
            libudev-dev libdbus-1-dev libwayland-dev libxkbcommon-dev \
            wayland-protocols

      - name: Install dependencies (Windows)
        if: matrix.platform.name == 'win-x64'
        run: |
          sudo apt update
          sudo apt install -y cmake mingw-w64 make

      - name: Create build folder
        shell: bash
        run: mkdir build

      - name: Configure SDL2 (Windows)
        if: matrix.platform.name == 'win-x64'
        shell: bash
        working-directory: build
        run: |
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_SYSTEM_PROCESSOR=x86_64 \
            -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
            -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
            -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/out

      - name: Configure SDL2 (Linux)
        if: matrix.platform.name == 'linux-x64'
        shell: bash
        working-directory: build
        run: |
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/out

      - name: Build SDL2
        shell: bash
        working-directory: build
        run: make -j$(nproc)

      - name: Install SDL2
        shell: bash
        working-directory: build
        run: make install

      - name: Prepare staging directory
        shell: bash
        run: mkdir -p dist/runtimes/${{ matrix.platform.name }}/native

      - name: Transfer SDL2 outputs (Windows)
        if: matrix.platform.name == 'win-x64'
        shell: bash
        run: cp out/bin/SDL2.dll dist/runtimes/${{ matrix.platform.name }}/native/

      - name: Transfer SDL2 outputs (Linux)
        if: matrix.platform.name == 'linux-x64'
        shell: bash
        run: cp out/lib/libSDL2.so dist/runtimes/${{ matrix.platform.name }}/native/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "native-${{ matrix.platform.name }}"
          path: "dist/"  
  
  package:
    runs-on: windows-latest
    needs: [ prepare, build-native ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: latest

      - name: Package preview
        if: github.event.action != 'published'
        shell: pwsh
        run: nuget pack Hyjinx.SDL2.native.nuspec -OutputDirectory ./out -Suffix "${{ needs.prepare.outputs.version_suffix }}" -Version "${{ needs.prepare.outputs.version_number }}"

      - name: Package release
        if: github.event.action == 'published'
        shell: pwsh
        run: nuget pack Hyjinx.SDL2.native.nuspec -OutputDirectory ./out -Version "${{ needs.prepare.outputs.version_number }}"
        
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./out/*.nupkg
    
  publish:
    runs-on: windows-latest
    needs: package
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: dist/

      - name: Set up NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: latest
          
      - name: Push package(s)
        shell: powershell
        run: |
          Get-ChildItem -Path "dist" -Filter *.nupkg | ForEach-Object {
            Write-Host "Pushing $($_.FullName)"
            nuget push $_.FullName -Source https://api.nuget.org/v3/index.json
          }

  post-publish:
    runs-on: ubuntu-latest
    needs: [ prepare, publish ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: dist/
          
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.prepare.outputs.full_version }}
          artifacts: "dist/*.*"
          prerelease: ${{ github.event.action != 'published' }}
          generateReleaseNotes: ${{ github.event.action != 'published' }}
          allowUpdates: true
          omitBodyDuringUpdate: true
